[CmdletBinding(DefaultParameterSetName = 'Files')]
param(
    [Parameter(Mandatory, ParameterSetName = 'Files')][string[]] $TranscriptPath,
    [Parameter(Mandatory, ParameterSetName = 'Directory')][string] $SessionsPath,
    [Parameter(Mandatory)][string] $OutputJson
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$markerPrefix = 'CODEX_DELIVERY_MARKER:'
$tokenNames = @('input_tokens', 'output_tokens', 'cached_tokens', 'reasoning_tokens', 'total_tokens')

function Get-Property([object]$Value, [string]$Name) { if ($null -eq $Value) { return $null }; if ($Value -is [System.Collections.IDictionary]) { if ($Value.Contains($Name)) { return $Value[$Name] }; return $null }; $p = $Value.PSObject.Properties[$Name]; if ($null -eq $p) { return $null }; return $p.Value }
function Get-String([object]$Value, [string]$Name) { $v = Get-Property $Value $Name; if ($v -is [string] -and -not [string]::IsNullOrWhiteSpace($v)) { return $v }; return $null }
function Get-Number([object]$Value, [string]$Name) { $v = Get-Property $Value $Name; if ($null -eq $v) { return $null }; if ($v -is [long] -or $v -is [int]) { if([long]$v -lt 0){$script:invalidNative=$true;return $null}; return [long]$v }; $script:invalidNative=$true; return $null }
function Get-Strings([object]$Value, [string]$Name) { $v=Get-Property $Value $Name; if ($null -eq $v) { return @() }; return @($v | ForEach-Object { if ($_ -is [string] -and $_) { $_ } } | Sort-Object -Unique) }
function Add-Unique([System.Collections.Generic.HashSet[string]]$Set, [string]$Value) { if (-not [string]::IsNullOrWhiteSpace($Value)) { [void]$Set.Add($Value) } }
function Get-OutputMarkers([object]$OutputWrapper) {
    $strings = [System.Collections.Generic.List[string]]::new(); $output=Get-Property $OutputWrapper 'output'; if($output -is [string]){[void]$strings.Add($output)}elseif($null -ne $output){foreach($item in @($output)){$text=Get-String $item 'text';if($text){[void]$strings.Add($text)}}}
    foreach ($text in $strings) { foreach($line in $text -split "`r?`n") { if(-not $line.StartsWith($markerPrefix,[StringComparison]::Ordinal)){continue};$json=$line.Substring($markerPrefix.Length);try{$marker=$json|ConvertFrom-Json -AsHashtable -Depth 8;if($marker.schemaVersion -eq 1){$marker}}catch{} } }
}
function Get-EventTimestamp([object]$Event) { foreach($n in @('timestamp','timestamp_utc','created_at')) { $v=Get-Property $Event $n; if($null -ne $v){ try { return [DateTimeOffset]::Parse([string]$v,[Globalization.CultureInfo]::InvariantCulture) } catch {} } }; return $null }
function Get-Usage([object]$Event) { $found=@{}; $names=@{input_tokens='input_tokens';output_tokens='output_tokens';cached_tokens='cached_input_tokens';reasoning_tokens='reasoning_output_tokens';total_tokens='total_tokens'}; foreach ($root in @($Event, (Get-Property $Event 'payload'), (Get-Property (Get-Property $Event 'payload') 'usage'), (Get-Property (Get-Property (Get-Property $Event 'payload') 'info') 'total_token_usage'))) { if ($null -eq $root) { continue }; foreach($n in $tokenNames) { if(-not $found.ContainsKey($n)){ $v=Get-Number $root $n; if($null -eq $v -and $names[$n] -ne $n){$v=Get-Number $root $names[$n]}; if($null -ne $v){$found[$n]=$v} } } }; if($found.Count){return $found}; return $null }
function Get-DurationMs([object]$Event) { foreach($root in @($Event,(Get-Property $Event 'payload'))) { $v=Get-Number $root 'duration_ms'; if($null -ne $v){return $v} }; return $null }

$files = if ($PSCmdlet.ParameterSetName -eq 'Directory') { @(Get-ChildItem -LiteralPath $SessionsPath -Filter '*.jsonl' -File -Recurse) } else { @($TranscriptPath | ForEach-Object { Get-Item -LiteralPath $_ }) }
$rows=[System.Collections.Generic.List[object]]::new();$totalTokensBySource=@{};$resultsBySource=@{}
foreach($file in $files) {
    $uuidMatch=[regex]::Match($file.Name,'(?<id>[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})')
    if(-not $uuidMatch.Success){ [void]$rows.Add([ordered]@{scope='session';source=$file.FullName;sourceCoverage='unavailable';schemaCoverage='unavailable';attributionCoverage='unavailable';reason='filename lacks rollout UUID'}); continue }
    $wanted=$uuidMatch.Groups['id'].Value.ToLowerInvariant(); $events=@(); $bad=$false
    foreach($line in [IO.File]::ReadLines($file.FullName)){ if([string]::IsNullOrWhiteSpace($line)){continue}; try{$events += ($line|ConvertFrom-Json -Depth 32)}catch{$bad=$true} }
    $meta=@($events | Where-Object { (Get-String $_ 'type') -eq 'session_meta' -and (Get-String (Get-Property $_ 'payload') 'id') -eq $wanted })
    if($meta.Count -ne 1){ [void]$rows.Add([ordered]@{scope='session';source=$file.FullName;sourceCoverage='partial';schemaCoverage=if($bad){'partial'}else{'unavailable'};attributionCoverage='unavailable';reason='owning session_meta missing or ambiguous'}); continue }
    $payload=Get-Property $meta[0] 'payload'; $sessionId=Get-String $payload 'id'; $source=Get-Property $payload 'source'; $spawn=Get-Property (Get-Property $source 'subagent') 'thread_spawn'; $parent=if($spawn){Get-String $spawn 'parent_thread_id'}else{(Get-String $payload 'parent_thread_id'),(Get-String $payload 'parent_id')|Where-Object{$_}|Select-Object -First 1}; $agentPath=if($spawn){Get-String $spawn 'agent_path'}else{Get-String $payload 'agent_path'}; $cwd=Get-String $payload 'cwd'; $repo=Get-String $payload 'repo'; $branch=Get-String $payload 'branch'; $startSha=Get-String $payload 'start_sha'; $cli=Get-String $payload 'cli_version'; $unknown=$false; $script:invalidNative=$false
    $models=[System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal); $efforts=[System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal); $toolStatuses=[System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal); $tools=0L;$toolMs=0L;$completeTurns=0L;$incompleteTurns=0L;$compactions=0L;$turnMs=0L;$ttft=$null;$times=[System.Collections.Generic.List[DateTimeOffset]]::new();$usageSeries=@{};foreach($n in $tokenNames){$usageSeries[$n]=[System.Collections.Generic.List[long]]::new()};$markers=[System.Collections.Generic.List[hashtable]]::new()
    foreach($event in $events){ $time=Get-EventTimestamp $event;if($time){[void]$times.Add($time)}; $type=Get-String $event 'type';$p=Get-Property $event 'payload';$eventType=Get-String $p 'type';if($type -notmatch '^(session_meta|turn_context|event_msg|response_item|inter_agent_communication_metadata|world_state|turn_[a-z-]+|tool|tool_[a-z-]+|compaction|rate_limits)$'){$unknown=$true}; Add-Unique $models (Get-String $p 'model'); Add-Unique $efforts (Get-String $p 'effort'); Add-Unique $efforts (Get-String $p 'reasoning_effort'); if($type -match 'compaction'){ $compactions++ }; if($type -match 'tool' -or ($type -eq 'response_item' -and $eventType -match 'tool_call$')){ $tools++; Add-Unique $toolStatuses (Get-String $p 'status'); $d=Get-DurationMs $event;if($null -ne $d){$toolMs+=$d}; if($type -match '^tool_(output|completed)$'){ foreach($marker in Get-OutputMarkers $p){[void]$markers.Add($marker)} } }; if($type -match 'turn' -or ($type -eq 'event_msg' -and $eventType -eq 'task_complete')){ if($eventType -eq 'task_complete' -or (Get-String $p 'status') -eq 'completed'){$completeTurns++}elseif((Get-String $p 'status')){$incompleteTurns++};$d=Get-DurationMs $p;if($null -ne $d){$turnMs+=$d};$candidateTtft=Get-Number $p 'time_to_first_token_ms';if($null -ne $candidateTtft){$ttft=$candidateTtft} }; if($type -match '^(turn|tool)' -or ($type -eq 'event_msg' -and $eventType -eq 'token_count')){ $usage=Get-Usage $event;if($usage){foreach($n in $usage.Keys){[void]$usageSeries[$n].Add([long]$usage[$n])}} } }
    foreach($event in $events){$p=Get-Property $event 'payload';if((Get-String $event 'type') -ne 'response_item'){continue};$eventType=Get-String $p 'type';if($eventType -eq 'function_call'){$tools++;Add-Unique $toolStatuses (Get-String $p 'status')};if($eventType -match '^(custom_tool_call_output|function_call_output)$'){foreach($marker in Get-OutputMarkers $p){[void]$markers.Add($marker)}}}
    $context=$null;$conflict=$false;$markerIndex=0;foreach($m in $markers){$has=@($m.ContainsKey('runId'),$m.ContainsKey('workItem'),$m.ContainsKey('role'));if(($has -contains $true) -and ($has -contains $false)){$conflict=$true;break};if($markerIndex -eq 0 -and $has -contains $false){$conflict=$true;break};if($has -notcontains $false){if($null -eq $context){$context=[ordered]@{runId=$m.runId;workItem=$m.workItem;role=$m.role}}elseif($context.runId -ne $m.runId -or $context.workItem -ne $m.workItem -or $context.role -ne $m.role){$conflict=$true;break}};$markerIndex++}
    if($conflict){ [void]$rows.Add([ordered]@{scope='session';source=$file.FullName;sessionId=$sessionId;sourceCoverage='partial';schemaCoverage='partial';attributionCoverage='complete';markerCoverage='rejected';reason='conflicting or incomplete marker context'}); continue }
    $totals=[ordered]@{};foreach($n in $tokenNames){$sum=0L;$previous=$null;foreach($value in $usageSeries[$n]){if($null -eq $previous -or $value -lt $previous){$sum+=$value}else{$sum+=($value-$previous)};$previous=$value};$totals[$n]=if($usageSeries[$n].Count -gt 0){$sum}else{$null}}
    $totalTokensBySource[$file.FullName]=$totals.total_tokens;$first=if($times.Count){($times|Sort-Object|Select-Object -First 1)}else{$null};$last=if($times.Count){($times|Sort-Object|Select-Object -Last 1)}else{$null};$phase=@($markers|ForEach-Object{Get-Property $_ 'phase'}|Where-Object{$_}|Sort-Object -Unique);$quality=@($markers|ForEach-Object{Get-Property $_ 'qualityOutcome'}|Where-Object{$_});$results=@($markers|ForEach-Object{Get-Property $_ 'result'}|Where-Object{$_}|Sort-Object -Unique);$resultsBySource[$file.FullName]=$results;$outcomes=@($markers|ForEach-Object{Get-Property $_ 'outcome'}|Where-Object{$_}|Sort-Object -Unique)
    [void]$rows.Add([ordered]@{scope='session';source=$file.FullName;sourceCoverage=if($bad -or $unknown -or $script:invalidNative){'partial'}else{'complete'};schemaCoverage=if($bad -or $unknown -or $script:invalidNative){'partial'}else{'best-effort'};attributionCoverage='complete';markerCoverage=if($markers.Count){'complete'}else{'unavailable'};cliVersion=$cli;sessionId=$sessionId;parentSessionId=$parent;agentPath=$agentPath;cwd=$cwd;repo=$repo;branch=$branch;startSha=$startSha;models=@($models|Sort-Object);efforts=@($efforts|Sort-Object);firstTimestamp=$first;lastTimestamp=$last;wallSpanSeconds=if($first -and $last){[math]::Round(($last-$first).TotalSeconds,3)}else{$null};activeTurnSeconds=if($turnMs){[math]::Round($turnMs/1000,3)}else{$null};timeToFirstTokenMs=$ttft;completedTurns=$completeTurns;incompleteTurns=$incompleteTurns;toolCount=$tools;toolStatuses=@($toolStatuses|Sort-Object);toolDurationSeconds=if($toolMs){[math]::Round($toolMs/1000,3)}else{$null};compactions=$compactions;inputTokens=$totals.input_tokens;outputTokens=$totals.output_tokens;cachedTokens=$totals.cached_tokens;reasoningTokens=$totals.reasoning_tokens;creditCoverage='unavailable';runId=if($context){$context.runId}else{$null};workItem=if($context){$context.workItem}else{$null};role=if($context){$context.role}else{$null};phases=$phase;workCycles=@($markers|Where-Object{(Get-Property $_ 'workCycle') -eq $true}).Count;qualityOutcomes=$quality;findingCount=(@($markers|ForEach-Object{Get-Property $_ 'findingCount'}|Where-Object{$null -ne $_}|Measure-Object -Sum).Sum);resolvedFindingCount=(@($markers|ForEach-Object{Get-Property $_ 'resolvedFindingCount'}|Where-Object{$null -ne $_}|Measure-Object -Sum).Sum);outcomes=$outcomes})
}
foreach($row in $rows){[void]$row.Remove('agentPath');if($totalTokensBySource.ContainsKey($row.source)){$row.totalTokens=$totalTokensBySource[$row.source]};if($resultsBySource.ContainsKey($row.source)){$row.results=$resultsBySource[$row.source]}}
$sessions=@($rows|Where-Object{(Get-Property $_ 'scope') -eq 'session' -and (Get-Property $_ 'workItem')});$work=@();foreach($group in $sessions|Group-Object runId,workItem){$items=@($group.Group);$first=@($items|ForEach-Object{Get-Property $_ 'firstTimestamp'}|Where-Object{$_}|Sort-Object|Select-Object -First 1);$last=@($items|ForEach-Object{Get-Property $_ 'lastTimestamp'}|Where-Object{$_}|Sort-Object|Select-Object -Last 1);$work += [ordered]@{scope='work-item';runId=(Get-Property $items[0] 'runId');workItem=(Get-Property $items[0] 'workItem');sessionCount=$items.Count;wallSpanSeconds=if($first.Count -and $last.Count){[math]::Round(($last[0]-$first[0]).TotalSeconds,3)}else{$null};summedActiveTurnSeconds=@($items|ForEach-Object{Get-Property $_ 'activeTurnSeconds'}|Where-Object{$null -ne $_}|Measure-Object -Sum).Sum;completedTurns=@($items|ForEach-Object{Get-Property $_ 'completedTurns'}|Measure-Object -Sum).Sum;incompleteTurns=@($items|ForEach-Object{Get-Property $_ 'incompleteTurns'}|Measure-Object -Sum).Sum;toolCount=@($items|ForEach-Object{Get-Property $_ 'toolCount'}|Measure-Object -Sum).Sum;compactions=@($items|ForEach-Object{Get-Property $_ 'compactions'}|Measure-Object -Sum).Sum;creditCoverage='unavailable';sourceCoverage=if(($items|ForEach-Object{Get-Property $_ 'sourceCoverage'}) -contains 'partial'){'partial'}else{'complete'}}}
foreach($item in $work){$item.results=@($sessions|Where-Object{(Get-Property $_ 'runId') -eq $item.runId -and (Get-Property $_ 'workItem') -eq $item.workItem}|ForEach-Object{Get-Property $_ 'results'}|ForEach-Object{$_}|Where-Object{$_}|Sort-Object -Unique)}
[ordered]@{schemaVersion=1;source='codex-transcript-backfill';sessions=$rows;workItems=$work} | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath $OutputJson -Encoding utf8
